In [1]:
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm

import scopesim as sim
import scopesim_templates as sim_tp

cluster = sim_tp.stellar.clusters.cluster(mass=1000,         # Msun
                                          distance=50000,    # parsec
                                          core_radius=0.3,   # parsec
                                          seed=9002)


micado = sim.OpticalTrain("MICADO")
micado.observe(cluster)
hdus = micado.readout()
# micado.readout(filename="TEST.fits")

fig, ax = plt.subplots(1,1,figsize=(10,8))
im = ax.imshow(hdus[0][1].data, norm=LogNorm(vmax=3E4, vmin=3E3), cmap="hot")
ax.set_title("Big Dank")
plt.colorbar(mappable=im, ax=ax)
plt.show()

Exception raised trying to POST request http://etimecalret-001.eso.org/observing/etc/api/skycalc
HTTPConnectionPool(host='etimecalret-001.eso.org', port=80): Max retries exceeded with url: /observing/etc/api/skycalc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BA9FB5BDC8>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

ERROR - Could not connect to skycalc server
Traceback (most recent call last):
  File "C:\Users\krist\Anaconda3\lib\site-packages\urllib3\connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\krist\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\krist\Anaconda3\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo

ValueError: Could not connect to skycalc server

In [3]:
len([1])

1

In [5]:
anything = {"thesame":3,"thesame":7}
anything["thesame"]

7

In [1]:
import numpy as np

In [4]:
a = np.array([[1,2,3],[4,5,6]])
b = np.ones(a.shape)

In [5]:
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
a.shape

(2, 3)

In [7]:
np.arange(1000,10000,1)

array([1000, 1001, 1002, ..., 9997, 9998, 9999])

In [8]:
np.linspace(1000,10000,1)

array([1000.])